# Target config - applies when using mips-nintendo64-none.json
[target.mips-nintendo64-none]
runner = ["nust64", "--ipl3", "ipl3_dummy.bin"]
rustflags = ["-C", "link-arg=-Tn64.ld"]

[alias]
# Build ROM: cargo +nightly n64-build --features embed_assets
n64-build = "build -Z build-std=core,alloc --target mips-nintendo64-none.json --release"

[build]
# Default target for this project
target = "mips-nintendo64-none.json"

